[workspace]
members = [
    "firmware/lpc812-mbed-xpresso",
    "firmware/ssd1322",
    "firmware/graphics",
]

[profile.dev]
codegen-units = 1
debug = true
lto = true
panic = "abort"
opt-level = "s"

[profile.release]
codegen-units = 1
debug = false
lto = true
panic = "abort"
opt-level = "s"
